general:
  general:
    backend: default
    imshow_origin: upper
    zoom_around_mask: true
  inversion:
    reconstruction_vmax_factor: 0.5
  units:
    in_kpc: false
include:
  include_1d:
    mask: false
    origin: false
  include_2d:
    border: true
    grid: false
    mapper_data_mesh_grid: true
    mapper_source_grid_slim: false
    mapper_source_mesh_grid: false
    mask: true
    origin: false
    parallel_overscan: true
    positions: true
    serial_overscan: true
    serial_prescan: true
mat_wrap:
  Axis:
    figure: {}
    subplot: {}
  Cmap:
    figure:
      cmap: default
      linscale: 0.01
      linthresh: 0.05
      norm: linear
      vmax: null
      vmin: null
    subplot:
      cmap: default
      linscale: 0.01
      linthresh: 0.05
      norm: linear
      vmax: null
      vmin: null
  Colorbar:
    figure:
      fraction: 0.047
      pad: 0.01
    subplot:
      fraction: 0.047
      pad: 0.01
  ColorbarTickParams:
    figure:
      labelsize: 10
    subplot:
      labelsize: 10
  Figure:
    figure:
      aspect: square
      figsize: (7,7)
    subplot:
      aspect: square
      figsize: auto
  Legend:
    figure:
      fontsize: 12
      include: true
    subplot:
      fontsize: 12
      include: true
  Text:
    figure:
      fontsize: 16
    subplot:
      fontsize: 10
  TickParams:
    figure:
      labelsize: 16
    subplot:
      labelsize: 10
  Title:
    figure:
      fontsize: 16
    subplot:
      fontsize: 10
  XLabel:
    figure:
      fontsize: 16
    subplot:
      fontsize: 10
  XTicks:
    figure:
      fontsize: 16
    subplot:
      fontsize: 10
  YLabel:
    figure:
      fontsize: 16
    subplot:
      fontsize: 10
  YTicks:
    figure:
      fontsize: 16
    subplot:
      fontsize: 10
mat_wrap_1d:
  AXVLine:
    figure:
      c: k
    subplot:
      c: k
  FillBetween:
    figure:
      alpha: 0.7
      color: k
    subplot:
      alpha: 0.7
      color: k
  YXPlot:
    figure:
      c: k
    subplot:
      c: k
  YXScatter:
    figure:
      c: k
    subplot:
      c: k
mat_wrap_2d:
  ArrayOverlay:
    figure:
      alpha: 0.5
    subplot:
      alpha: 0.5
  BorderScatter:
    figure:
      c: r
      marker: .
      s: 30
    subplot:
      c: r
      marker: .
      s: 10
  GridErrorbar:
    figure:
      alpha: 0.5
      c: k
      fmt: o
      linewidth: 5
      marker: o
      markersize: 8
    subplot:
      alpha: 0.5
      c: k
      fmt: o
      linewidth: 5
      marker: o
      markersize: 8
  GridPlot:
    figure:
      c: k
    subplot:
      c: k
  GridScatter:
    figure:
      c: k
      marker: .
      s: 1
    subplot:
      c: k
      marker: .
      s: 1
  IndexScatter:
    figure:
      c: r,g,b,m,y,k
      marker: .
      s: 20
    subplot:
      c: r,g,b,m,y,k
      marker: .
      s: 20
  MaskScatter:
    figure:
      c: k
      marker: x
      s: 10
    subplot:
      c: k
      marker: x
      s: 10
  MeshGridScatter:
    figure:
      c: r
      marker: .
      s: 2
    subplot:
      c: r
      marker: .
      s: 2
  OriginScatter:
    figure:
      c: k
      marker: x
      s: 80
    subplot:
      c: k
      marker: x
      s: 80
  ParallelOverscanPlot:
    figure:
      c: k
      linestyle: '-'
      linewidth: 1
      pointsize: 20
    subplot:
      c: k
      linestyle: '-'
      linewidth: 1
      pointsize: 20
  PatchOverlay:
    figure:
      edgecolor: c
      facecolor: null
    subplot:
      edgecolor: c
      facecolor: null
  PositionsScatter:
    figure:
      c: k,m,y,b,r,g
      marker: .
      s: 16
    subplot:
      c: k,m,y,b,r,g
      marker: .
      s: 16
  SerialOverscanPlot:
    figure:
      c: k
      linestyle: '-'
      linewidth: 1
      pointsize: 20
    subplot:
      c: k
      linestyle: '-'
      linewidth: 1
      pointsize: 20
  SerialPrescanPlot:
    figure:
      c: k
      linestyle: '-'
      linewidth: 1
      pointsize: 20
    subplot:
      c: k
      linestyle: '-'
      linewidth: 1
      pointsize: 20
  VectorYXQuiver:
    figure:
      alpha: 1.0
      angles: xy
      headlength: 0
      headwidth: 1
      linewidth: 5
      pivot: middle
      units: xy
    subplot:
      alpha: 1.0
      angles: xy
      headlength: 0
      headwidth: 1
      linewidth: 5
      pivot: middle
      units: xy
  VoronoiDrawer:
    figure:
      alpha: 0.7
      edgecolor: k
      linewidth: 0.3
    subplot:
      alpha: 0.7
      edgecolor: k
      linewidth: 0.3
